# Generated by Django 4.0.3 on 2022-03-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
